server:
  port: 8085
spring:
  kafka:
    producer:
      acks: -1
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS_PRODUCER}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer